config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  get 'home/index' #controller/acction
  root 'home#index'
  
  resources :reservations #resources cria as 8 rotas de forma automática
  resources :books
  resources :authors
  resources :librarians
  resources :categories
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Outra forma de criar rotas: 
  #only:[:new], show] (mostra somente esses)
  #except: :edit (exclui)
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :category
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    options_for_select
  end

  # GET /authors/1/edit
  def edit
    options_for_select
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def options_for_select
      @category_options_for_select = Category.all
    end
     # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :category_id)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= collection_select(:author, :category_id, @category_options_for_select, :id, :description) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="box">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Authors</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tbody><tr>
            <th>Name</th><th>Category</th>
          </tr>
            <tr>
              <td>Chad Lind V</td>
              <td>Historical fiction</td>
              <td><a href="/authors/1">Show</a></td>
              <td><a href="/authors/1/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/1">Destroy</a></td>
            </tr>
            <tr>
              <td>Gracie Volkman</td>
              <td>Fairy tale</td>
              <td><a href="/authors/2">Show</a></td>
              <td><a href="/authors/2/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/2">Destroy</a></td>
            </tr>
            <tr>
              <td>Byron Ledner</td>
              <td>Comic/Graphic Novel</td>
              <td><a href="/authors/3">Show</a></td>
              <td><a href="/authors/3/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/3">Destroy</a></td>
            </tr>
            <tr>
              <td>Vanessa Koelpin</td>
              <td>Comic/Graphic Novel</td>
              <td><a href="/authors/4">Show</a></td>
              <td><a href="/authors/4/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/4">Destroy</a></td>
            </tr>
            <tr>
              <td>Athena Nitzsche Sr.</td>
              <td>Historical fiction</td>
              <td><a href="/authors/5">Show</a></td>
              <td><a href="/authors/5/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/5">Destroy</a></td>
            </tr>
            <tr>
              <td>Maryjane Stamm</td>
              <td>Folklore</td>
              <td><a href="/authors/6">Show</a></td>
              <td><a href="/authors/6/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/6">Destroy</a></td>
            </tr>
            <tr>
              <td>Mrs. Apolonia Bernhard</td>
              <td>Speech</td>
              <td><a href="/authors/7">Show</a></td>
              <td><a href="/authors/7/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/7">Destroy</a></td>
            </tr>
            <tr>
              <td>Nicholas Kerluke</td>
              <td>Speech</td>
              <td><a href="/authors/8">Show</a></td>
              <td><a href="/authors/8/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/8">Destroy</a></td>
            </tr>
            <tr>
              <td>Miss Ivana Jacobi</td>
              <td>Science fiction</td>
              <td><a href="/authors/9">Show</a></td>
              <td><a href="/authors/9/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/9">Destroy</a></td>
            </tr>
            <tr>
              <td>Gavin Haley</td>
              <td>Science fiction</td>
              <td><a href="/authors/10">Show</a></td>
              <td><a href="/authors/10/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/authors/10">Destroy</a></td>
            </tr>
        </tbody></table>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div>
    <a class="btn btn-primary" style="color: white;" href="/authors/new">New Author</a>
  </div>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @author.category %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>