config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  get 'home/index' #controller/acction
  root 'home#index'
  
  resources :reservations #resources cria as 8 rotas de forma automática
  resources :books
  resources :authors
  resources :librarians
  resources :categories
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Outra forma de criar rotas: 
  #only:[:new], show] (mostra somente esses)
  #except: :edit (exclui)
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :telephone, :CPF)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :CPF %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Clients</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tbody><tr>
            <th>Name</th><th>Telephone</th><th>CPF</th>
          </tr>
            <tr>
              <td>Antonio Boyle Morar</td>
              <td>500-926-4350</td>
              <td>55219781667</td>
              <td><a href="/clients/1">Show</a></td>
              <td><a href="/clients/1/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/1">Destroy</a></td>
            </tr>
            <tr>
              <td>Mrs. Cristobal Predovic Abbott</td>
              <td>215-904-1516</td>
              <td>19020926423</td>
              <td><a href="/clients/2">Show</a></td>
              <td><a href="/clients/2/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/2">Destroy</a></td>
            </tr>
            <tr>
              <td>Ned Lowe Von</td>
              <td>(654) 176-8903</td>
              <td>25374100844</td>
              <td><a href="/clients/3">Show</a></td>
              <td><a href="/clients/3/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/3">Destroy</a></td>
            </tr>
            <tr>
              <td>Miss Sylvia Lesch Hauck</td>
              <td>1-384-363-3316</td>
              <td>37922100119</td>
              <td><a href="/clients/4">Show</a></td>
              <td><a href="/clients/4/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/4">Destroy</a></td>
            </tr>
            <tr>
              <td>Almeda Weber Bradtke</td>
              <td>361.691.1130</td>
              <td>24955602360</td>
              <td><a href="/clients/5">Show</a></td>
              <td><a href="/clients/5/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/5">Destroy</a></td>
            </tr>
            <tr>
              <td>Wilber Collier Stark</td>
              <td>744.420.9834</td>
              <td>29695322608</td>
              <td><a href="/clients/6">Show</a></td>
              <td><a href="/clients/6/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/6">Destroy</a></td>
            </tr>
            <tr>
              <td>Darwin Denesik Emard</td>
              <td>684-521-0072</td>
              <td>42642051605</td>
              <td><a href="/clients/7">Show</a></td>
              <td><a href="/clients/7/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/7">Destroy</a></td>
            </tr>
            <tr>
              <td>Kristopher Mraz Mertz</td>
              <td>(192) 346-6313</td>
              <td>86190535457</td>
              <td><a href="/clients/8">Show</a></td>
              <td><a href="/clients/8/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/8">Destroy</a></td>
            </tr>
            <tr>
              <td>Miss Imelda Hermann Lockman</td>
              <td>1-591-139-6665</td>
              <td>78712584569</td>
              <td><a href="/clients/9">Show</a></td>
              <td><a href="/clients/9/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/9">Destroy</a></td>
            </tr>
            <tr>
              <td>Josue Upton Little</td>
              <td>885-980-8324</td>
              <td>47231519813</td>
              <td><a href="/clients/10">Show</a></td>
              <td><a href="/clients/10/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/clients/10">Destroy</a></td>
            </tr>
        </tbody></table>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div>
    <a class="btn btn-primary" style="color: white;" href="/clients/new">New Client</a>
  </div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @client.telephone %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @client.CPF %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>