config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  get 'home/index' #controller/acction
  root 'home#index'
  
  resources :reservations #resources cria as 8 rotas de forma automática
  resources :books
  resources :authors
  resources :librarians
  resources :categories
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Outra forma de criar rotas: 
  #only:[:new], show] (mostra somente esses)
  #except: :edit (exclui)
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Category</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tbody><tr>
            <th>Description</th>
          </tr>
            <tr>
              <td>Speech</td>
              <td><a href="/categories/1">Show</a></td>
              <td><a href="/categories/1/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/1">Destroy</a></td>
            </tr>
            <tr>
              <td>Historical fiction</td>
              <td><a href="/categories/2">Show</a></td>
              <td><a href="/categories/2/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/2">Destroy</a></td>
            </tr>
            <tr>
              <td>Humor</td>
              <td><a href="/categories/3">Show</a></td>
              <td><a href="/categories/3/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/3">Destroy</a></td>
            </tr>
            <tr>
              <td>Tall tale</td>
              <td><a href="/categories/4">Show</a></td>
              <td><a href="/categories/4/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/4">Destroy</a></td>
            </tr>
            <tr>
              <td>Science fiction</td>
              <td><a href="/categories/5">Show</a></td>
              <td><a href="/categories/5/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/5">Destroy</a></td>
            </tr>
            <tr>
              <td>Tirra Lirra by the River</td>
              <td><a href="/categories/6">Show</a></td>
              <td><a href="/categories/6/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/6">Destroy</a></td>
            </tr>
            <tr>
              <td>Folklore</td>
              <td><a href="/categories/7">Show</a></td>
              <td><a href="/categories/7/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/7">Destroy</a></td>
            </tr>
            <tr>
              <td>Folklore</td>
              <td><a href="/categories/8">Show</a></td>
              <td><a href="/categories/8/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/8">Destroy</a></td>
            </tr>
            <tr>
              <td>Comic/Graphic Novel</td>
              <td><a href="/categories/9">Show</a></td>
              <td><a href="/categories/9/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/9">Destroy</a></td>
            </tr>
            <tr>
              <td>Tall tale</td>
              <td><a href="/categories/10">Show</a></td>
              <td><a href="/categories/10/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/categories/10">Destroy</a></td>
            </tr>
        </tbody></table>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div>
    <a class="btn btn-primary" style="color: white;" href="/categories/new">New Category</a>
  </div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>