config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  get 'home/index' #controller/acction
  root 'home#index'
  
  resources :reservations #resources cria as 8 rotas de forma automática
  resources :books
  resources :authors
  resources :librarians
  resources :categories
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Outra forma de criar rotas: 
  #only:[:new], show] (mostra somente esses)
  #except: :edit (exclui)
end

app/models/librarian.rb
class Librarian < ApplicationRecord
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.all
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def librarian_params
      params.require(:librarian).permit(:name, :email)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Librarians</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tbody><tr>
            <th>Name</th><th>Email</th>
          </tr>
            <tr>
              <td>Taylor Kertzmann</td>
              <td>mikki@ebert.ion</td>
              <td><a href="/librarians/1">Show</a></td>
              <td><a href="/librarians/1/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/1">Destroy</a></td>
            </tr>
            <tr>
              <td>Star Hessel V</td>
              <td>otis_lindgren@bins.org</td>
              <td><a href="/librarians/2">Show</a></td>
              <td><a href="/librarians/2/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/2">Destroy</a></td>
            </tr>
            <tr>
              <td>Ute Hintz</td>
              <td>chelsea.schimmel@reynolds.net</td>
              <td><a href="/librarians/3">Show</a></td>
              <td><a href="/librarians/3/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/3">Destroy</a></td>
            </tr>
            <tr>
              <td>Ligia Bode</td>
              <td>vincenzo.gulgowski@champlin.name</td>
              <td><a href="/librarians/4">Show</a></td>
              <td><a href="/librarians/4/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/4">Destroy</a></td>
            </tr>
            <tr>
              <td>Dana Larson</td>
              <td>susanna@will-swaniawski.net</td>
              <td><a href="/librarians/5">Show</a></td>
              <td><a href="/librarians/5/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/5">Destroy</a></td>
            </tr>
            <tr>
              <td>Shin Schimmel</td>
              <td>brian.oreilly@quigley-ritchie.info</td>
              <td><a href="/librarians/6">Show</a></td>
              <td><a href="/librarians/6/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/6">Destroy</a></td>
            </tr>
            <tr>
              <td>Ms. Nolan Boyle</td>
              <td>alisia.muller@harvey.org</td>
              <td><a href="/librarians/7">Show</a></td>
              <td><a href="/librarians/7/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/7">Destroy</a></td>
            </tr>
            <tr>
              <td>Miss Evan Bogisich</td>
              <td>gale@johnson.io</td>
              <td><a href="/librarians/8">Show</a></td>
              <td><a href="/librarians/8/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/8">Destroy</a></td>
            </tr>
            <tr>
              <td>Rigoberto Jacobi</td>
              <td>otto.nader@herzog.info</td>
              <td><a href="/librarians/9">Show</a></td>
              <td><a href="/librarians/9/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/9">Destroy</a></td>
            </tr>
            <tr>
              <td>Jenine Kuhn</td>
              <td>dennis@langosh-schneider.name</td>
              <td><a href="/librarians/10">Show</a></td>
              <td><a href="/librarians/10/edit">Edit</a></td>
              <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/librarians/10">Destroy</a></td>
            </tr>
        </tbody></table>
      </div>
      <!-- /.box-body -->
    </div>
  </div>

  <div>
    <a class="btn btn-primary" style="color: white" href="/librarians/new">New Category</a>
  </div>

app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Back', librarians_path %>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @librarian.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @librarian.email %>
</p>

<%= link_to 'Edit', edit_librarian_path(@librarian) %> |
<%= link_to 'Back', librarians_path %>